Tried to fix git-branch-menu so that I could use it to delete the (invalid?) branches created by git-svn, but gave up.
It seems that:
    git branch -D 'refs/remotes/1.10.0'
    error: branch '1.10.0' not found.
works just about as well as:
    git branch -D '1.10.0'
    error: branch '1.10.0' not found.